### ISSUE TITLE
Probably mistaken name: myTexTheme. Is It myTextTheme?

### ISSUE THREAD

**Issue by seikosantana** [seikosantana/gampah#3]

**Comment by Bintaaaa** [comment]
we must to change it

**Comment by seikosantana** [comment]
Will do. Will refactor every reference to `appTextTheme`. This will be a breaking change to many widgets in the project.

**Comment by seikosantana** [comment]
Please see https://github.com/seikosantana/gampah/commit/3e3dae788fc724d63ea5456e3334048102367034 and fast-forward to this commit to prevent potential conflicts in the future. I will close this issue. Please reopen if necessary.

**Comment by Bintaaaa** [comment]
oke done
