### ISSUE TITLE
where is the navigation back button? sometimes it goes to getStartedPage or blank page.

### ISSUE THREAD

**Issue by Bintaaaa** [seikosantana/gampah#6]
![Screenshot_20211129-022852](https://user-images.githubusercontent.com/79687063/143783033-fe2f2295-c29f-494e-8524-424ff8cb2410.png)

**Comment by Bintaaaa** [comment]
I changed the navigation, have you received my pull?

**Comment by seikosantana** [comment]
I investigated this and seems like the issue is caused by the `CustomToolbarWidget` using `pop` while the profile widget ~~is not navigated using `push`.~~ We replaced named and it changes the tree, not appending into it so pop leads to the root tree.

**Comment by seikosantana** [comment]
https://github.com/seikosantana/gampah/blob/bf51551769c4d1a4814ced895bfb5931260a881c/lib/ui/pages/page_profile.dart#L26-L28

https://github.com/seikosantana/gampah/blob/bf51551769c4d1a4814ced895bfb5931260a881c/lib/ui/widgets/widget_toolbar.dart#L5-L20

https://github.com/seikosantana/gampah/blob/bf51551769c4d1a4814ced895bfb5931260a881c/lib/ui/pages/page_home.dart#L68-L70

**Comment by seikosantana** [comment]
Other possible cause
https://stackoverflow.com/questions/53723294/flutter-navigator-popcontext-returning-a-black-screen

**Comment by Bintaaaa** [comment]
if you have accepted my pull and you have run it should not need to be changed again

**Comment by seikosantana** [comment]
I did pulled but It still happens on my end

**Comment by seikosantana** [comment]
Weird. No longer happening.

**Comment by Bintaaaa** [comment]
if it happens again please do a "flutter clean" in your terminal

**Comment by seikosantana** [comment]
Noted.
