### ISSUE TITLE
after register not navigate to navigator

### ISSUE THREAD

**Issue by Bintaaaa** [seikosantana/gampah#7]
i need help for this, please check branch [https://github.com/seikosantana/gampah/tree/integration-with-api](url) and running in your devices

**Comment by Bintaaaa** [comment]
it solved but I still have doubts because it only turns on comments on models at variable token in fromJson. may be you have any solution for this issue?

**Comment by seikosantana** [comment]
I will look into this but i will be looking at after finishing the API part.
